services:
  db:
    image: mysql:8.0
    container_name: qa-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: qadb
      MYSQL_USER: ${SPRING_DATASOURCE_USERNAME}
      MYSQL_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      TZ: Asia/Tokyo
    ports:
      - '3306:3306'
    command:
      [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_0900_ai_ci',
      ]
    volumes:
      - qa_mysql_data:/var/lib/mysql

volumes:
  qa_mysql_data:
